services:
  db:
    image: postgres:alpine
    container_name: poker-db
    restart: always
    environment:
      POSTGRES_USER: dennis
      POSTGRES_PASSWORD: super_hemligt
      POSTGRES_DB: poker_db
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:alpine
    container_name: poker-redis
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: poker-api
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__AzureStorage=DefaultEndpointsProtocol=https;AccountName=${AZURE_STORAGE_ACCOUNT};AccountKey=${AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net
      - Redis__ConnectionString=poker-redis:6379
      - OpenAI__APIKey=${OPENAI_API_KEY}
      - OpenAI__Model=${OPENAI_MODEL}
      - AzureStorage__ServiceUri=https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/
      - AzureStorage__ContainerName=${AZURE_STORAGE_CONTAINER}
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: http://localhost:5000
    container_name: poker-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  postgres_data: