<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FluentResults">
      <HintPath>..\..\..\.nuget\packages\fluentresults\4.0.0\lib\net9.0\FluentResults.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
